# Generated by Django 2.2.12 on 2020-04-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y%m%d/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
