# Generated by Django 2.2.12 on 2020-04-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
        ('products', '0002_auto_20200417_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='farm.Farm'),
        ),
    ]
