# Generated by Django 2.2.12 on 2020-04-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/eggs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_main',
            field=models.ImageField(upload_to='photos/eggs'),
        ),
    ]
